version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/usr/src
      - puma-socket:/var/run/puma
    ports:
      - 3000:3000
  web:
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./docker/nginx/certs:/etc/nginx/certs
      - puma-socket:/var/run/puma
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
volumes:
  puma-socket:
